<?php
/**
 * Chic Centre Suites — custom i18n layer.
 *
 * Path-prefix model: English (default) has no prefix; Greek lives under /el/.
 * Uses WordPress query_vars + add_rewrite_rule; no Polylang/WPML dependency.
 */
defined( 'ABSPATH' ) || exit;

/* ── Constants ───────────────────────────────────────────────────────────── */

define( 'CHIC_DEFAULT_LANG',    'en' );
define( 'CHIC_SUPPORTED_LANGS', [ 'en', 'el' ] );
define( 'CHIC_I18N_VERSION',    '2' );

/* ── Language detection ──────────────────────────────────────────────────── */

function chic_get_current_lang(): string {
	static $lang = null;
	if ( null !== $lang ) {
		return $lang;
	}
	$qv = (string) get_query_var( 'lang', '' );
	if ( $qv && in_array( $qv, CHIC_SUPPORTED_LANGS, true ) ) {
		$lang = $qv;
		return $lang;
	}
	$path     = trim( (string) parse_url( $_SERVER['REQUEST_URI'] ?? '/', PHP_URL_PATH ), '/' );
	$segments = explode( '/', $path );
	if ( ! empty( $segments[0] ) && in_array( $segments[0], [ 'el' ], true ) ) {
		$lang = $segments[0];
		return $lang;
	}
	$lang = CHIC_DEFAULT_LANG;
	return $lang;
}

/* ── Rewrite rules ───────────────────────────────────────────────────────── */

add_action( 'init', function () {
	add_rewrite_rule( '^el/?$',          'index.php?lang=el',                          'top' );
	add_rewrite_rule( '^el/(.+?)/?$',    'index.php?lang=el&pagename=$matches[1]',     'top' );
	// Registered last so WP checks it first among `top` rules: Greek MotoPress singles.
	add_rewrite_rule(
		'^el/accommodation/([^/]+)/?$',
		'index.php?lang=el&post_type=mphb_room_type&name=$matches[1]',
		'top'
	);
}, 1 );

add_filter( 'query_vars', function ( array $vars ): array {
	$vars[] = 'lang';
	return $vars;
} );

// Remap Greek request vars before parse_query runs, so WP sets conditionals correctly.
add_filter( 'request', function ( array $query_vars ): array {
	if ( ( $query_vars['lang'] ?? '' ) !== 'el' ) {
		return $query_vars;
	}

	// Remap pagename=accommodation/slug to the accommodation CPT.
	$pagename = $query_vars['pagename'] ?? '';
	if ( is_string( $pagename ) && '' !== $pagename
		&& preg_match( '#^accommodation/([^/]+)$#', $pagename, $m ) ) {
		unset( $query_vars['pagename'] );
		$query_vars['post_type'] = 'mphb_room_type';
		$query_vars['name']      = $m[1];
		return $query_vars;
	}

	// Bare /el/ → inject the static front page's slug so parse_query resolves it as
	// a normal page request (sets is_page + is_front_page correctly, before templates
	// are chosen). Setting page_id in pre_get_posts was too late — conditionals were
	// already baked in, causing the parent theme's home.php to load instead.
	if ( empty( $query_vars['pagename'] )
		&& empty( $query_vars['name'] )
		&& empty( $query_vars['page_id'] )
		&& empty( $query_vars['p'] )
		&& 'page' === get_option( 'show_on_front' ) ) {
		$front_id = (int) get_option( 'page_on_front' );
		if ( $front_id > 0 ) {
			$front = get_post( $front_id );
			if ( $front instanceof WP_Post && 'publish' === $front->post_status ) {
				$query_vars['pagename'] = $front->post_name;
			}
		}
	}

	return $query_vars;
}, 5 );

// Flush rewrite rules on theme activation.
add_action( 'after_switch_theme', function () {
	flush_rewrite_rules();
} );

// Flush when our version bumps.
add_action( 'init', function () {
	if ( get_option( 'chic_i18n_version' ) !== CHIC_I18N_VERSION ) {
		flush_rewrite_rules();
		update_option( 'chic_i18n_version', CHIC_I18N_VERSION );
	}
}, 99 );

/* ── Physical /el/ directory shim ────────────────────────────────────────── */

/**
 * The Sitemap & LLMs.txt tool writes el/llms.txt, which forces a real `el`
 * directory into ABSPATH. That directory shadows our `^el/?$` rewrite rule.
 * WordPress's root .htaccess skips existing directories (RewriteCond !-d), so
 * the server tries to serve the folder itself and returns 403 Forbidden when
 * directory listing is off, which is the case on every production host.
 *
 * The tool drops an el/.htaccess to route around it, but that only helps on
 * Apache with AllowOverride enabled. An index.php inside the directory works
 * on Apache, Nginx and LiteSpeed alike. The server resolves it as the
 * DirectoryIndex, it boots WordPress, and WP matches /el/ against its own
 * rewrite rules exactly as if the directory never existed.
 *
 * Bump CHIC_EL_SHIM_VERSION to force a rewrite of the shim on next admin load.
 */
define( 'CHIC_EL_SHIM_VERSION', '1' );

function chic_el_dir_shim_contents(): string {
	return <<<'PHP'
<?php
/**
 * Auto-generated by the Chic Centre Suites child theme. Do not edit.
 * @see inc/i18n.php, function chic_el_ensure_dir_shim()
 *
 * The physical el/ directory (created to host el/llms.txt) shadows the theme's
 * ^el/?$ rewrite rule, so the server never hands /el/ to WordPress and returns
 * 403. This file is the DirectoryIndex for that folder. It boots WordPress,
 * which then matches the untouched REQUEST_URI (/el/) against its own rules.
 */
require dirname( __DIR__ ) . '/index.php';
PHP;
}

/**
 * Write el/index.php if the physical directory exists and the shim is missing
 * or out of date. Never creates the directory. If there is no el/ folder then
 * the rewrite rules already work and there is nothing to fix.
 */
function chic_el_ensure_dir_shim(): bool {
	$dir = ABSPATH . 'el';
	if ( ! is_dir( $dir ) ) {
		return false;
	}

	$shim     = $dir . '/index.php';
	$contents = chic_el_dir_shim_contents();

	if ( is_file( $shim ) ) {
		$existing = (string) file_get_contents( $shim );
		if ( $existing === $contents ) {
			return true;
		}
		// Only overwrite a file we generated ourselves, never a hand-written one.
		if ( false === strpos( $existing, 'chic_el_ensure_dir_shim' ) ) {
			return false;
		}
	}

	return false !== file_put_contents( $shim, $contents, LOCK_EX );
}

// Self-heal on admin load, once per shim version.
add_action( 'admin_init', function () {
	if ( get_option( 'chic_el_shim_version' ) === CHIC_EL_SHIM_VERSION ) {
		return;
	}
	chic_el_ensure_dir_shim();
	update_option( 'chic_el_shim_version', CHIC_EL_SHIM_VERSION );
} );

/* ── Canonical redirect guard ────────────────────────────────────────────── */

add_filter( 'redirect_canonical', function ( $redirect_url, $requested_url ) {
	$path = trim( (string) parse_url( $requested_url ?? $_SERVER['REQUEST_URI'] ?? '/', PHP_URL_PATH ), '/' );
	if ( strncmp( $path, 'el/', 3 ) === 0 || $path === 'el' ) {
		return false;
	}
	return $redirect_url;
}, 10, 2 );

/* ── HTML lang attribute ─────────────────────────────────────────────────── */

add_filter( 'language_attributes', function ( string $output ): string {
	$map = [
		'en' => 'en-US',
		'el' => 'el-GR',
	];
	$lang = chic_get_current_lang();
	if ( isset( $map[ $lang ] ) ) {
		return 'lang="' . esc_attr( $map[ $lang ] ) . '"';
	}
	return $output;
} );

/* ── Translation helpers ─────────────────────────────────────────────────── */

function chic_get_translations( string $lang ): array {
	static $cache = [];
	if ( isset( $cache[ $lang ] ) ) {
		return $cache[ $lang ];
	}
	if ( $lang === CHIC_DEFAULT_LANG ) {
		$cache[ $lang ] = [];
		return $cache[ $lang ];
	}
	$file = get_stylesheet_directory() . '/translations/' . $lang . '.php';
	$cache[ $lang ] = file_exists( $file ) ? include $file : [];
	return $cache[ $lang ];
}

function t( string $key ): string {
	$lang = chic_get_current_lang();
	if ( $lang === CHIC_DEFAULT_LANG ) {
		return $key;
	}
	$map = chic_get_translations( $lang );
	return $map[ $key ] ?? $key;
}

/**
 * Greek translation from translations/el.php regardless of current locale.
 * Used by ACF seeding/backfill in wp-admin where chic_get_current_lang() is always en.
 */
function t_el( string $en ): string {
	$map = chic_get_translations( 'el' );
	return $map[ $en ] ?? $en;
}

function te( string $key ): void {
	echo esc_html( t( $key ) );
}

function ta( string $key ): string {
	return esc_attr( t( $key ) );
}

function t_html( string $key ): string {
	return t( $key );
}

/**
 * Strip monotonic Greek tonos / dialytika for copy shown in all-caps UI (see theme CSS).
 * No-op when not on Greek locale or when intl Normalizer is unavailable (limited fallback).
 */
function chic_el_strip_monotonic_tonos( string $text ): string {
	if ( $text === '' || chic_get_current_lang() !== 'el' ) {
		return $text;
	}
	static $precomposed = [
		'Ά' => 'Α', 'Έ' => 'Ε', 'Ή' => 'Η', 'Ί' => 'Ι', 'Ό' => 'Ο', 'Ύ' => 'Υ', 'Ώ' => 'Ω',
		'Ϊ' => 'Ι', 'Ϋ' => 'Υ',
	];
	$text = strtr( $text, $precomposed );
	if ( class_exists( 'Normalizer', false ) ) {
		$norm = Normalizer::normalize( $text, Normalizer::FORM_D );
		if ( is_string( $norm ) && '' !== $norm ) {
			$norm = preg_replace( '/[\x{0301}\x{0308}\x{0342}\x{0344}\x{0345}]/u', '', $norm );
			$nfc  = Normalizer::normalize( $norm, Normalizer::FORM_C );
			if ( is_string( $nfc ) ) {
				$text = $nfc;
			} else {
				$text = $norm;
			}
		}
	} else {
		static $lower = [
			'ά' => 'α', 'έ' => 'ε', 'ή' => 'η', 'ί' => 'ι', 'ό' => 'ο', 'ύ' => 'υ', 'ώ' => 'ω',
			'ϊ' => 'ι', 'ΐ' => 'ι', 'ϋ' => 'υ', 'ΰ' => 'υ',
		];
		$text = strtr( $text, $lower );
	}
	return $text;
}

/** Translation for all-caps / uppercase-styled Greek (buttons, certain headings). */
function t_uc( string $key ): string {
	return chic_el_strip_monotonic_tonos( t( $key ) );
}

function te_uc( string $key ): void {
	echo esc_html( t_uc( $key ) );
}

function ta_uc( string $key ): string {
	return esc_attr( t_uc( $key ) );
}

function t_uc_html( string $key ): string {
	return chic_el_strip_monotonic_tonos( t_html( $key ) );
}

/* ── Suite title translation helper ─────────────────────────────────────── */

function chic_translate_suite_title( string $english_title ): string {
	if ( chic_get_current_lang() === CHIC_DEFAULT_LANG ) {
		return $english_title;
	}
	// "Forest Suite" → "Σουίτα Forest"
	if ( preg_match( '/^(.+?)\s+Suite$/i', $english_title, $m ) ) {
		return t( 'Suite' ) . ' ' . $m[1];
	}
	// "Suite 3" → "Σουίτα 3"
	if ( preg_match( '/^Suite\s+(.+)$/i', $english_title, $m ) ) {
		return t( 'Suite' ) . ' ' . $m[1];
	}
	return $english_title;
}

/** Suite title for `.suite-card__title` / `.suite-hero__title` (all-caps CSS); keeps tonos in `chic_translate_suite_title()` for other uses. */
function chic_translate_suite_title_uc( string $english_title ): string {
	return chic_el_strip_monotonic_tonos( chic_translate_suite_title( $english_title ) );
}

/* ── URL builders ────────────────────────────────────────────────────────── */

function chic_localized_url( string $path = '/', ?string $lang = null ): string {
	$lang = $lang ?? chic_get_current_lang();
	$path = '/' . ltrim( $path, '/' );
	if ( $lang === CHIC_DEFAULT_LANG ) {
		return home_url( $path );
	}
	return home_url( '/' . $lang . $path );
}

/**
 * Prefix absolute permalinks with /el/ on Greek front-end requests.
 */
function chic_localize_front_permalink( string $url ): string {
	if ( '' === $url || CHIC_DEFAULT_LANG === chic_get_current_lang() ) {
		return $url;
	}
	if ( is_admin() ) {
		return $url;
	}
	$rel = wp_make_link_relative( $url );
	if ( $rel === $url || '' === $rel ) {
		return $url;
	}
	return chic_localized_url( $rel );
}

add_filter(
	'post_type_link',
	function ( string $post_link, $post, $leavename = false, $sample = false ): string {
		if ( $sample || ! $post instanceof WP_Post || 'mphb_room_type' !== $post->post_type ) {
			return $post_link;
		}
		return chic_localize_front_permalink( $post_link );
	},
	10,
	4
);

add_filter(
	'page_link',
	function ( string $link, int $post_id, bool $sample = false ): string {
		if ( $sample ) {
			return $link;
		}
		return chic_localize_front_permalink( $link );
	},
	10,
	3
);

function chic_lang_switch_url( string $target_lang ): string {
	$raw_path  = (string) parse_url( $_SERVER['REQUEST_URI'] ?? '/', PHP_URL_PATH );
	$clean     = trim( $raw_path, '/' );
	// Strip existing language prefix (el) from the path.
	foreach ( CHIC_SUPPORTED_LANGS as $code ) {
		if ( $code === CHIC_DEFAULT_LANG ) continue;
		if ( strncmp( $clean, $code . '/', strlen( $code ) + 1 ) === 0 ) {
			$clean = substr( $clean, strlen( $code ) + 1 );
			break;
		}
		if ( $clean === $code ) {
			$clean = '';
			break;
		}
	}
	if ( $target_lang === CHIC_DEFAULT_LANG ) {
		return home_url( '/' . ( $clean ? $clean . '/' : '' ) );
	}
	return home_url( '/' . $target_lang . '/' . ( $clean ? $clean . '/' : '' ) );
}

/* ── Browser-language redirect (first visit) ─────────────────────────────── */

add_action( 'template_redirect', function () {
	$path = trim( (string) parse_url( $_SERVER['REQUEST_URI'] ?? '/', PHP_URL_PATH ), '/' );
	if ( $path !== '' ) return;
	if ( ! empty( $_COOKIE['mci_lang'] ) ) return;

	// Skip known crawlers.
	$ua = strtolower( $_SERVER['HTTP_USER_AGENT'] ?? '' );
	if ( preg_match( '/bot|crawl|spider|slurp|bing|yandex|baidu|duckduckbot|facebookexternalhit|twitterbot|googlebot/', $ua ) ) {
		return;
	}

	$accept  = $_SERVER['HTTP_ACCEPT_LANGUAGE'] ?? '';
	$matched = null;
	// Parse quality values.
	$parts = explode( ',', $accept );
	$langs_q = [];
	foreach ( $parts as $part ) {
		$part = trim( $part );
		if ( preg_match( '/^([a-zA-Z]{1,8}(?:-[a-zA-Z0-9]{1,8})?)\s*(?:;\s*q=([\d.]+))?$/', $part, $m ) ) {
			$code = strtolower( substr( $m[1], 0, 2 ) );
			$q    = isset( $m[2] ) ? (float) $m[2] : 1.0;
			if ( ! isset( $langs_q[ $code ] ) || $langs_q[ $code ] < $q ) {
				$langs_q[ $code ] = $q;
			}
		}
	}
	arsort( $langs_q );
	foreach ( array_keys( $langs_q ) as $code ) {
		if ( $code === 'el' ) { $matched = 'el'; break; }
	}

	if ( $matched ) {
		setcookie( 'mci_lang', $matched, [
			'expires'  => time() + 60 * 60 * 24 * 365,
			'path'     => '/',
			'samesite' => 'Lax',
		] );
		wp_safe_redirect( home_url( '/' . $matched . '/' ), 302 );
		exit;
	}

	setcookie( 'mci_lang', 'en', [
		'expires'  => time() + 60 * 60 * 24 * 365,
		'path'     => '/',
		'samesite' => 'Lax',
	] );
}, 5 );

// Sync cookie when user manually navigates to a prefixed URL.
add_action( 'template_redirect', function () {
	$lang = chic_get_current_lang();
	if ( $lang !== CHIC_DEFAULT_LANG && empty( $_COOKIE['mci_lang'] ) ) {
		setcookie( 'mci_lang', $lang, [
			'expires'  => time() + 60 * 60 * 24 * 365,
			'path'     => '/',
			'samesite' => 'Lax',
		] );
	}
}, 9 );

/* ── SEO: hreflang + AIOSEO filters ─────────────────────────────────────── */

// Emit hreflang alternates early in wp_head.
add_action( 'wp_head', function () {
	if ( is_admin() ) return;

	$raw_path = (string) parse_url( $_SERVER['REQUEST_URI'] ?? '/', PHP_URL_PATH );
	$clean    = trim( $raw_path, '/' );
	foreach ( CHIC_SUPPORTED_LANGS as $code ) {
		if ( $code === CHIC_DEFAULT_LANG ) continue;
		if ( strncmp( $clean, $code . '/', strlen( $code ) + 1 ) === 0 ) {
			$clean = substr( $clean, strlen( $code ) + 1 );
			break;
		}
		if ( $clean === $code ) {
			$clean = '';
			break;
		}
	}
	$base_path = $clean ? '/' . $clean . '/' : '/';

	$en_url      = home_url( $base_path );
	$el_url      = home_url( '/el' . $base_path );
	$default_url = $en_url;

	echo '<link rel="alternate" hreflang="en" href="' . esc_url( $en_url ) . '">' . "\n";
	echo '<link rel="alternate" hreflang="el" href="' . esc_url( $el_url ) . '">' . "\n";
	echo '<link rel="alternate" hreflang="x-default" href="' . esc_url( $default_url ) . '">' . "\n";
}, 1 );

// Swap AIOSEO title/description (including OG + Twitter) to Greek on /el/ routes.
$chic_aioseo_swap = function ( $value, string $meta_key ) {
	if ( chic_get_current_lang() === 'el' && is_singular() ) {
		$greek = get_post_meta( get_the_ID(), $meta_key, true );
		if ( $greek ) return $greek;
	}
	return $value;
};

add_filter( 'aioseo_title',                fn ( $v ) => $chic_aioseo_swap( $v, '_chic_aioseo_title_el' ) );
add_filter( 'aioseo_description',          fn ( $v ) => $chic_aioseo_swap( $v, '_chic_aioseo_description_el' ) );
add_filter( 'aioseo_facebook_title',       fn ( $v ) => $chic_aioseo_swap( $v, '_chic_aioseo_title_el' ) );
add_filter( 'aioseo_facebook_description', fn ( $v ) => $chic_aioseo_swap( $v, '_chic_aioseo_description_el' ) );
add_filter( 'aioseo_twitter_title',        fn ( $v ) => $chic_aioseo_swap( $v, '_chic_aioseo_title_el' ) );
add_filter( 'aioseo_twitter_description',  fn ( $v ) => $chic_aioseo_swap( $v, '_chic_aioseo_description_el' ) );

// Force prefixed canonical URL for Greek pages.
add_filter( 'aioseo_canonical_url', function ( $url ) {
	if ( chic_get_current_lang() === 'el' ) {
		$path = (string) parse_url( $url, PHP_URL_PATH );
		return chic_localized_url( $path ?: '/' );
	}
	return $url;
} );

// Set OG locale for Greek pages.
add_filter( 'aioseo_facebook_locale', function ( $locale ) {
	if ( chic_get_current_lang() === 'el' ) {
		return 'el_GR';
	}
	return $locale;
} );
